# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  
  fileSystems."/".neededForBoot = true;
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/39291c25-29d2-42a5-b0f9-70d10db83fdd";
      fsType = "xfs";
    };

  fileSystems."/efi" =
    { device = "systemd-1";
      fsType = "autofs";
    };
  

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B2A8-80AD";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" "users" "nofail" ];
    };
  
  systemd.tmpfiles.rules = [ "d /mnt 0755 ishdeshpa ishdeshpa" ];
  fileSystems."/mnt" =
    { device = "/dev/disk/by-uuid/636320c7-2118-4663-a6e4-d52f8b79a554";
      fsType = "ext4";
      options = [ 
          "users" # Allows any user to mount and unmount
          "nofail" # Prevent system from failing if this drive doesn't mount
          "exec" # exec
          ];
    };

  swapDevices = [
    {
      device = "/var/lib/swap/swapfile";
      priority = 100;
    }
  ];
  boot.resumeDevice = "/dev/disk/by-uuid/39291c25-29d2-42a5-b0f9-70d10db83fdd"; # UUID of the partition where swapfile is
  boot.kernelParams = [
    "resume_offset=58465342"
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
